# Toekomst

Het is lastig om voor te stellen waar ik na het afronden van deze
studie terecht zal komen. Het gebied "Life Sciences" is namelijk zo
ongelofelijk breed dat er bijna in elke sector wel een mogelijk beroep
te bedenken valt. Het is mij in ieder geval wel duidelijk dat onderzoek
doen het beste bij mij past. Ik word het meest enthousiast wanneer ik
nieuwe dingen kan leren. Daarom overweeg ik om een master te gaan doen
als vervolg op mijn studie.

Een mogelijk onderwerp waar ik me verder in wil verdiepen tijdens mijn
stage en eventueel master is immunologie. Van alle theorievakken uit
deze bachelor vond ik deze het meest interessant. Veel immunologisch
onderzoek is toegewijd aan het ontwikkelen van next-generation
immunotherapy (denk aan CAR-T). Een aantal analyses die veel worden
gebruikt zijn single-cell RNA-seq analysis tools, single-cell
multi-omics integration tools en machine learning tools.

Geen van deze skills zijn in volledigheid behandeld tijdens de cursus
data sciences. Wel hebben we een introductie gehad in het analyseren
van RNA-seq data. Twee analyses die me leuk lijken om in te verdiepen
tijdens de vrije ruimte zijn single-cell RNA-sequencing en het gebruik
van machine learning/large language models.