# Project ALS database

ALS (amyotrofische laterale sclerose) is een zenuw- en spierziekte waarbij zenuwcellen in het ruggenmerg afsterven waardoor spieren één voor één uitvallen. Ruim 200 duizend mensen wereldwijd leven met ALS. Op dit moment is er nog geen goede behandeling voor patiënten met ALS[@ZiekteALS].

Project MinE is een project gecoördineerd door Kevin Kenna, een onderzoeker bij het UMC Utrecht. MinE bestaat uit een samenwerking tussen 27 centra die samenwerken om alle genetische varianten van ALS in kaart te brengen. Ze hebben als doel om het genoom van 15 duizend ALS-patiënten en 7,5 duizend controles te analyseren[@Home2022]. De genetische varianten komen in een relationele database te staan die beschikbaar is voor artsen en onderzoekers.

Vanwege de aard van de database is het alleen mogelijk om informatie te onttrekken met SQL-commando's. Omdat de meeste mensen niet bekend zijn met SQL, moeten onderzoekers van project MinE zelf aanvragen van artsen verwerken die specifieke informatie uit de databank nodig hebben. Om de database toegankelijker te maken is het idee ontstaan om hiervoor een LLM te gebruiken. Artsen kunnen vragen stellen aan de LLM, en deze zoekt dan op de juiste plek in de database en combineert de juiste tabellen om een correct antwoord te kunnen geven.

De eerste opzet maakte gebruik van Querychat[@QueryChatInteractiveData]. Dit programma koppelt de LLM aan de database en zorgt ervoor dat deze de juiste tools heeft om de database in te zien. Querychat heeft echter het probleem dat het de LLM enkel toegang geeft tot één tabel van de database, terwijl deze uit meerdere tabellen bestaat. Het werd al snel duidelijk dat Querychat geen goede optie is om de LLM en de databank mee te koppelen.

Een andere optie die ter sprake kwam is het ontwikkelen van een MCP (Model Context Protocol). Een MCP is een soort toolkit die een LLM kan gebruiken om taken uit te voeren. In plaats van dat Querychat de connectie legt tussen de LLM en de databank, doet de MCP dat. MCP's zijn volledig aanpasbaar naar de behoefte van de ontwikkelaar. Je bepaalt zelf welke tools er in de MCP zitten en dus welke functies de LLM kan uitvoeren. Door functies toe te voegen die SQL kunnen uitvoeren, heeft de LLM de mogelijkheid om de databank in te zien [@WhatModelContext].

De MCP moet aan een aantal voorwaarden voldoen. Ten eerste moet deze lokaal draaien. De ALS-databank bevat gevoelige informatie over patiënten, dus er mag geen mogelijkheid zijn dat deze op het internet terechtkomt. Verder moet de LLM/MCP in staat zijn om altijd een correct antwoord te geven en moet worden voorkomen dat de LLM gaat hallucineren (antwoorden verzinnen). Tot slot is er de voorkeur om het R-pakket RVAT te integreren in de opzet. RVAT is ontwikkeld speciaal voor rare variant analysis in grote RNA-sequencing datasets zoals de ALS-databank[@RareVariantAnalysis]. Het eindoel is om een R package te ontwikkelen van de door ons ontwikkelde MCP opzet.
